<?php $__env->startSection('header'); ?>
<?php echo $__env->make('front.sub_parts.header', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
<?php $__env->stopSection(); ?>
<?php echo $__env->yieldSection(); ?>
<?php $__env->startSection('content'); ?>

<?$title= "Privacy Policy | $website[name]" ?>
<?php $__env->startSection('title',$title); ?>
  <!-- terms -->
   <div class="container-fluid terms-conditions">
       <div class="row">
	      <div class="container">
		    <div class="row">
			    <div class="col-xs-12 heading">
				   <h1>Privacy Policy</h1>
				</div>
			</div>
		    <div class="row">
			    <div class="col-xs-12 contents">				   
				   <p>The following privacy notice explains our policy regarding the personal information we collect about you in the process of your cooperation with <span class="color"><?php echo $website['name']; ?></span> website. It applies to the information we collect about:</p>
				 
				   <ul>
				      <li>Visitors of our website.</li>
				      <li>People who use our services.</li>					 
				   </ul>
						<h4>Information we collect as you browse our website</h4>
						<p>Our web server automatically collects standard information, including your browser type, operating system and access time. We collect this information in a way, which does not identify anyone. We do not make any attempt to find out the identities of those visiting our website.</p>
						<p>This information is used only to improve the content of our web pages and to customize it and/or the layout of our pages. We never sell, rent or share any of the information we collect by this method (except anonymous aggregate information) with any third parties.</p>
						<p>We use Google Analytics to help analyze use of our website. This analytical tool uses 'cookies';, which are text files placed on your computer, to collect standard Internet log information and visitor behavior information in an anonymous form. The data generated by the cookie about your use of the website is transmitted to Google. This information is then used to evaluate visitors’ use of the website and to compile statistical reports on website’s activity. To find out more about cookies, including how to control and delete them, visit www.aboutcookies.org/. To opt out of being tracked by Google Analytics across all websites visit http://tools.google.com/dlpage/gaoptout.</p>
						<h4>Information we collect when you use our services</h4>
						<p>When you start your cooperation with us, you will be asked to provide personal information in order to perform payments for our services, control the process of your order fulfillment and receive the completed piece of writing. We may use any contact information (emails and phone numbers) submitted to this website. We have to hold the details of the people who have requested the service in order to provide it. However, we only use these details to provide the service the person has requested and for other closely related purposes. We will use your email address to send you notifications considering the most important stages of order fulfillment, such as clarification of any issues, unread messages and order completion. Your email and telephone number may also be used for promotional and marketing purposes, to notify you of special offers and discounts, etc.</p>
						<p>This information will be used only by our Customer Support Representatives and will not on any condition be disclosed to any third party; it is never sold, rented or shared.</p>
						<p>All the information in the order, inquiry pages and personal control panel is processed with the use of the SSL-certificate, which guarantees complete confidentiality and safety of all the transactions.</p>
						<h4>Complaints or queries</h4>
						<p>We try to meet the highest standards when collecting and using personal information. For this reason, we take any complaints we receive about this very seriously. We encourage people to bring it to our attention if they think that our collection or use of information is unfair, misleading or inappropriate. We would also welcome any suggestions for improving our procedures.</p>
						<p>This privacy notice was drafted with brevity and clarity in mind. It does not provide exhaustive details of all the aspects of our collection and use of personal information. However, we are happy to provide any additional information or explanation needed. Any requests for this should be sent to our email.</p>
						<h4>Access to personal information</h4>
						<p>We try to be as open as we can in terms of giving people access to their personal information. Individuals can find out if we hold any personal information about them by making a "subject access request" under the Data Protection Act 1998. If we do hold information about you, we will:</p>
						<ul>
							<li>Give you a description of it;</li>
							<li>Tell you why we are holding it;</li>
							<li>Tell you to whom it could be disclosed;</li>
							<li>Let you have a copy of the information in an intelligible form.</li>
						</ul>
						<p>To make a request to us for any personal information we may need you to put the request in writing addressing it to our Customer Support Representatives via email. If you agree, we will try to deal with your request informally, for example by providing you with the specific information you need over the telephone. If we do hold information about you, you can ask us to correct any mistakes by, once again, contacting Customer Support Representatives.</p>
						<h4>Links Disclaimer</h4>
						<p>In order to provide visitors with certain information, this website provides links to local, state and federal government agencies, and websites of other organizations. A link does not constitute an endorsement of the content, viewpoint, accuracy, opinions, policies, products, services, or accessibility of that website. Once you link to another site from this website, including one maintained by the State, you are subject to the terms and conditions of that website, including, but not limited to, its privacy policy.</p>
				</div>
			</div>
		  </div>
	   </div>
   </div>
 <!-- terms -->




<?php $__env->stopSection(); ?>
<?php $__env->startSection('footer'); ?>
<?php echo $__env->make('front.sub_parts.footer', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->yieldSection(); ?>	
<?php echo $__env->make('front.layouts.master', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>